name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - .github/workflows/ci.yml
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - .github/workflows/ci.yml

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # needed because of parser dependencies
      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          test-parser-cmd: npm tree-sitter test
          test-rust: ${{runner.os == 'Linux'}}
