name: Github Release Tag

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    if: github.repository == 'Hdoc1509/tree-sitter-hygen-template'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Create release
        id: release_tag
        uses: yyx990803/release-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/Hdoc1509/tree-sitter-hygen-template/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
